import skimage.io as io
import matplotlib.pyplot as plt

img_prueba = io.imread('Zebra.jpeg')
img_prueba_clasificacion = io.imread('Clasificación_.jpg')
img_prueba_deteccion = io.imread('Detección.jpg')
img_prueba_segInstancias = io.imread('Segmentación_de_Instancias.jpg')
img_prueba_seg_Semantica = io.imread('Segmentación_Semántica.jpg')

fig, ax = plt.subplots(3,2)
fig.suptitle('Anotaciones')
ax[0][0].imshow(img_prueba)
ax[0][0].axis('off')
ax[0][0].set_title('Imagen a color')
ax[1][0].imshow(img_prueba_clasificacion)
ax[1][0].axis('off')
ax[1][0].set_title('Clasificación')
ax[2][0].imshow(img_prueba_seg_Semantica)
ax[2][0].axis('off')
ax[2][0].set_title('Segmentacón semántica')
ax[1][1].imshow(img_prueba_deteccion)
ax[1][1].axis('off')
ax[1][1].set_title('Detección')
ax[2][1].imshow(img_prueba_segInstancias)
ax[2][1].axis('off')
ax[2][1].set_title('Sementación instancias')
ax[0][1].axis('off')
plt.savefig('Figura_Anotaciones')
plt.show()